// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDahnvUDIb-AJheKc7uZ9qPmV1AF4n-D78',
    appId: '1:708147064634:web:c3c9d3e1100b8f655aaa03',
    messagingSenderId: '708147064634',
    projectId: 'nxllogin',
    authDomain: 'nxllogin.firebaseapp.com',
    storageBucket: 'nxllogin.firebasestorage.app',
    measurementId: 'G-FYE544KPZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZdtmqQrGw-My_d--AGiwkIVFJhkZfsGw',
    appId: '1:708147064634:android:ccb9e228b3d14d055aaa03',
    messagingSenderId: '708147064634',
    projectId: 'nxllogin',
    storageBucket: 'nxllogin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqLDT6ph-74mD0AsPMO7XWBb1hIHgJ1NM',
    appId: '1:708147064634:ios:187abe78e610ffc85aaa03',
    messagingSenderId: '708147064634',
    projectId: 'nxllogin',
    storageBucket: 'nxllogin.firebasestorage.app',
    iosBundleId: 'com.example.nxlLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqLDT6ph-74mD0AsPMO7XWBb1hIHgJ1NM',
    appId: '1:708147064634:ios:187abe78e610ffc85aaa03',
    messagingSenderId: '708147064634',
    projectId: 'nxllogin',
    storageBucket: 'nxllogin.firebasestorage.app',
    iosBundleId: 'com.example.nxlLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDahnvUDIb-AJheKc7uZ9qPmV1AF4n-D78',
    appId: '1:708147064634:web:9506af60e7f7fad55aaa03',
    messagingSenderId: '708147064634',
    projectId: 'nxllogin',
    authDomain: 'nxllogin.firebaseapp.com',
    storageBucket: 'nxllogin.firebasestorage.app',
    measurementId: 'G-3BWM98JJMJ',
  );
}
